[package]
name    = "bench_rust_gif"
version = "0.0.1"
authors = ["Nigel Tao <nigeltao@golang.org>"]

[dependencies]
gif     = "*"
rustc_version_runtime = "*"

[profile.release]
codegen-units = 1
opt-level = 3
panic = "abort"
